[package]
name = "uperf-actuator"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
crc32fast.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
uperf-core = { path = "../uperf-core" }
uperf-platform = { path = "../uperf-platform" }

[dev-dependencies]
uperf-testkit = { path = "../uperf-testkit" }

[lints]
workspace = true
